//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Utilities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alittlebit;abandon;abbreviation;aberration;abhor;abide;ability;abject;able;abnormality;aboard;abolish;abortion;abound;abroad;abrupt;absence;absent;absorb;abstain;absurd;abundance;abundant;abuse;abuse;abyss;accelerate;accept;acceptable;acceptance;access;accessory;accident;accident;accidental;accommodate;accommodation;accompany;accomplish;accomplishment;accord;accordance;according;accordingly;account;account;accountable;accountant;accuracy;accurate;accusation;accuse;accustom;ache;achieve;achievement;acid;ackn [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ENWords5000 {
            get {
                return ResourceManager.GetString("ENWords5000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to немного;покидать;сокращение;отклонение;ненавидеть;оставатьсяверным;способность;жалкий;способныйкчему;неправильность;наборту;отменять;аборт;изобиловать;заграницей;резкий;отсутствие;отсутствующий;поглощать;воздерживаться;нелепый;избыток;обильный;злоупотреблять;оскорблять;бездна;ускорять;приниматьилидопускать;приемлемый;принятие;доступ;принадлежность;случай;авария;случайный;приспосабливать;пристанище;сопровождать;совершить;достижение;согласовывать;согласие;всоответствиис;соответственно;счётвбанке;мнение;соотве [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RUWords5000 {
            get {
                return ResourceManager.GetString("RUWords5000", resourceCulture);
            }
        }
    }
}
